### ISSUE TITLE
Make stock tracker more mobile friendly

### ISSUE THREAD

**Issue by Etheriad** [Etheriad/tropical-cardboard#22] opened 2022-11-02 13:52 UTC
The stock tracker makes the vending machine really small since they are in line. Somehow, lets either hide, or move the stock tracker to allow the vending machine to be full size.

**Comment by CoryKlish** [comment] 2023-04-25 22:36
Duplicate of #28 / #29

**Closed by CoryKlish** 2023-04-25 22:36 UTC
